package com.gamaala.webseries;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import android.text.*;import java.io.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
 int BG=Color.rgb(9,10,14), PANEL=Color.rgb(19,21,28), CARD=Color.rgb(25,27,35), WHITE=Color.rgb(248,248,250), MUTED=Color.rgb(155,158,168), ACCENT=Color.rgb(255,190,55);
 FrameLayout screen; LinearLayout current; ArrayList<Item> data=new ArrayList<>(); HashSet<String> myList=new HashSet<>();
 static class Item{String title,kind,lang,genre,rating,poster;Item(JSONObject o){title=o.optString("title");kind=o.optString("kind");lang=o.optString("lang");genre=o.optString("genre");rating=o.optString("rating");poster=o.optString("poster");}}
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);screen=findViewById(R.id.screen);
  findViewById(R.id.navHome).setOnClickListener(v->home()); findViewById(R.id.navFind).setOnClickListener(v->find()); findViewById(R.id.navTv).setOnClickListener(v->shows()); findViewById(R.id.navDownload).setOnClickListener(v->list()); findViewById(R.id.navMe).setOnClickListener(v->list()); load(); home(); }
 void load(){try{InputStream in=getAssets().open("catalog.json");ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))>0)o.write(b,0,n);JSONArray a=new JSONObject(o.toString("UTF-8")).getJSONArray("items");for(int i=0;i<a.length();i++)data.add(new Item(a.getJSONObject(i)));}catch(Exception ignored){}}
 GradientDrawable shape(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
 TextView tv(String s,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setGravity(Gravity.CENTER_VERTICAL);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(WHITE);b.setTextSize(13);b.setBackgroundColor(Color.TRANSPARENT);b.setMinHeight(0);b.setMinWidth(0);return b;}
 void base(){screen.removeAllViews();ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setBackgroundColor(BG);LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(0,0,0,28);sv.addView(page);screen.addView(sv);current=page;}
 void home(){base();brandBar();searchBar();quickTabs();hero();rail("Popular Movies",0,5);rail("Popular Web Series",3,6);rail("Trending Now",0,10);sectionGenres();}
 void brandBar(){LinearLayout r=new LinearLayout(this);r.setPadding(18,14,18,2);r.setGravity(Gravity.CENTER_VERTICAL);TextView logo=tv("GAMA AALA",22,WHITE,true);r.addView(logo,new LinearLayout.LayoutParams(0,48,1));TextView bell=tv("♡",28,WHITE,false);bell.setGravity(Gravity.CENTER);r.addView(bell,new LinearLayout.LayoutParams(45,48));TextView avatar=tv("●",22,ACCENT,true);avatar.setGravity(Gravity.CENTER);r.addView(avatar,new LinearLayout.LayoutParams(45,48));current.addView(r);}
 void searchBar(){LinearLayout r=new LinearLayout(this);r.setPadding(16,4,16,8);EditText e=new EditText(this);e.setHint("Search movies, web series...");e.setHintTextColor(Color.rgb(115,118,128));e.setTextColor(WHITE);e.setTextSize(15);e.setSingleLine(true);e.setPadding(18,0,18,0);e.setBackground(shape(Color.rgb(28,30,38),55));e.setOnEditorActionListener((v,a,event)->{find();return true;});r.addView(e,new LinearLayout.LayoutParams(-1,54));current.addView(r);}
 void quickTabs(){LinearLayout r=new LinearLayout(this);r.setPadding(12,0,12,2);String[] names={"Home","Movies","Series","Anime"};for(String n:names){Button b=btn(n);b.setTextSize(14);b.setTextColor(n.equals("Home")?ACCENT:MUTED);r.addView(b,new LinearLayout.LayoutParams(0,46,1));if(n.equals("Movies"))b.setOnClickListener(v->movies());if(n.equals("Series"))b.setOnClickListener(v->shows());}current.addView(r);}
 void hero(){if(data.size()==0)return;Item x=data.get(0);LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(22,20,22,18);h.setBackground(shape(Color.rgb(34,35,42),24));TextView small=tv("GAMA AALA ORIGINALS",11,ACCENT,true);h.addView(small);h.addView(tv(x.title,29,WHITE,true));h.addView(tv("Premium entertainment • "+x.lang+" • ★ "+x.rating,13,MUTED,false));h.addView(tv("Watch the latest movies and web series in one place.",13,MUTED,false));LinearLayout buttons=new LinearLayout(this);buttons.setGravity(Gravity.CENTER_VERTICAL);Button watch=btn("▶  WATCH NOW");watch.setTextColor(Color.BLACK);watch.setBackground(shape(ACCENT,40));buttons.addView(watch,new LinearLayout.LayoutParams(150,48));Button add=btn("＋ My List");add.setTextColor(WHITE);buttons.addView(add,new LinearLayout.LayoutParams(120,48));h.addView(buttons);h.setOnClickListener(v->details(x));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,190);p.setMargins(12,8,12,12);current.addView(h,p);}
 void rail(String title,int start,int count){LinearLayout head=new LinearLayout(this);head.setPadding(18,8,12,4);TextView h=tv(title,20,WHITE,true);head.addView(h,new LinearLayout.LayoutParams(0,44,1));TextView more=tv("See all  ›",12,ACCENT,false);more.setGravity(Gravity.CENTER);head.addView(more,new LinearLayout.LayoutParams(72,44));current.addView(head);HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout row=new LinearLayout(this);row.setPadding(14,0,10,8);for(int i=start;i<Math.min(start+count,data.size());i++)addPoster(row,data.get(i));hs.addView(row);current.addView(hs);}
 void addPoster(LinearLayout row,Item x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);ImageView img=new ImageView(this);int id=getResources().getIdentifier(x.poster,"drawable",getPackageName());img.setImageResource(id);img.setScaleType(ImageView.ScaleType.CENTER_CROP);c.addView(img,new LinearLayout.LayoutParams(142,202));TextView name=tv(x.title,14,WHITE,true);name.setMaxLines(1);name.setEllipsize(TextUtils.TruncateAt.END);c.addView(name,new LinearLayout.LayoutParams(-1,28));c.addView(tv(x.lang+"   ★ "+x.rating,10,ACCENT,false),new LinearLayout.LayoutParams(-1,24));c.setOnClickListener(v->details(x));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(150,258);p.setMargins(4,0,8,0);row.addView(c,p);}
 void sectionGenres(){current.addView(tv("Browse by Genre",20,WHITE,true),new LinearLayout.LayoutParams(-1,46));LinearLayout r=new LinearLayout(this);r.setPadding(14,0,14,12);for(String g:new String[]{"Drama","Action","Comedy","Thriller","Animation","Sci-Fi"}){Button b=btn(g);b.setTextSize(12);b.setTextColor(WHITE);b.setBackground(shape(Color.rgb(31,33,42),32));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,44);p.setMargins(4,2,4,2);r.addView(b,p);b.setOnClickListener(v->genre(g));}HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);hs.addView(r);current.addView(hs);}
 void movies(){base();brandBar();searchBar();current.addView(tv("Movies",25,WHITE,true),new LinearLayout.LayoutParams(-1,48));for(Item x:data)if(x.kind.equals("Movie"))full(x);}
 void shows(){base();brandBar();searchBar();current.addView(tv("Web Series",25,WHITE,true),new LinearLayout.LayoutParams(-1,48));for(Item x:data)if(x.kind.equals("Series"))full(x);}
 void genre(String g){base();brandBar();searchBar();current.addView(tv(g,25,WHITE,true),new LinearLayout.LayoutParams(-1,48));for(Item x:data)if(x.genre.equalsIgnoreCase(g))full(x);}
 void full(Item x){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);c.setPadding(10,10,10,10);c.setBackground(shape(CARD,18));ImageView img=new ImageView(this);int id=getResources().getIdentifier(x.poster,"drawable",getPackageName());img.setImageResource(id);img.setScaleType(ImageView.ScaleType.CENTER_CROP);c.addView(img,new LinearLayout.LayoutParams(100,150));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setPadding(13,0,5,0);info.addView(tv(x.lang,10,Color.CYAN,true));info.addView(tv(x.title,18,WHITE,true));info.addView(tv(x.kind+"  •  "+x.genre,12,MUTED,false));info.addView(tv("★ "+x.rating,12,ACCENT,true));Button b=btn(myList.contains(x.title)?"♥ Saved":"＋ My List");b.setTextColor(WHITE);b.setOnClickListener(v->{if(myList.contains(x.title))myList.remove(x.title);else myList.add(x.title);b.setText(myList.contains(x.title)?"♥ Saved":"＋ My List");});info.addView(b);c.addView(info,new LinearLayout.LayoutParams(0,-1,1));c.setOnClickListener(v->details(x));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,170);p.setMargins(12,5,12,5);current.addView(c,p);}
 void details(Item x){base();brandBar();ImageView img=new ImageView(this);int id=getResources().getIdentifier(x.poster,"drawable",getPackageName());img.setImageResource(id);img.setScaleType(ImageView.ScaleType.CENTER_CROP);current.addView(img,new LinearLayout.LayoutParams(-1,300));current.addView(tv(x.title,28,WHITE,true),new LinearLayout.LayoutParams(-1,54));current.addView(tv(x.lang+"  •  "+x.kind+"  •  "+x.genre+"  •  ★ "+x.rating,13,ACCENT,false),new LinearLayout.LayoutParams(-1,42));current.addView(tv("Enjoy this title on GAMA AALA. Select an episode or start playback when available.",14,MUTED,false),new LinearLayout.LayoutParams(-1,80));Button play=btn("▶  PLAY NOW");play.setTextColor(Color.BLACK);play.setBackground(shape(ACCENT,38));current.addView(play,new LinearLayout.LayoutParams(-1,50));Button save=btn(myList.contains(x.title)?"♥ Saved":"＋ My List");save.setOnClickListener(v->{if(myList.contains(x.title))myList.remove(x.title);else myList.add(x.title);save.setText(myList.contains(x.title)?"♥ Saved":"＋ My List");});current.addView(save);}
 void find(){base();brandBar();searchBar();EditText e=new EditText(this);e.setHint("Search titles, genres, languages...");e.setTextColor(WHITE);e.setHintTextColor(Color.GRAY);e.setSingleLine(true);e.setTextSize(16);e.setPadding(18,0,18,0);e.setBackground(shape(Color.rgb(28,30,38),45));current.addView(e,new LinearLayout.LayoutParams(-1,52));LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);current.addView(results);e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){results.removeAllViews();String q=s.toString().toLowerCase();for(Item x:data)if(q.isEmpty()||x.title.toLowerCase().contains(q)||x.genre.toLowerCase().contains(q)||x.lang.toLowerCase().contains(q)) {LinearLayout old=current;current=results;full(x);current=old;}}public void afterTextChanged(Editable e){}});}
 void list(){base();brandBar();current.addView(tv("My List",25,WHITE,true),new LinearLayout.LayoutParams(-1,48));boolean any=false;for(Item x:data)if(myList.contains(x.title)){full(x);any=true;}if(!any)current.addView(tv("Your saved movies and series will appear here.",14,MUTED,false));}
}
